package routenames

const (
	Home                 = "home"
	About                = "about"
	Contact              = "contact"
	ContactSubmit        = "contact.submit"
	Login                = "login"
	LoginSubmit          = "login.submit"
	Register             = "register"
	RegisterSubmit       = "register.submit"
	ForgotPassword       = "forgot_password"
	ForgotPasswordSubmit = "forgot_password.submit"
	Logout               = "logout"
	VerifyEmail          = "verify_email"
	ResetPassword        = "reset_password"
	ResetPasswordSubmit  = "reset_password.submit"
	Search               = "search"
	Task                 = "task"
	TaskSubmit           = "task.submit"
	Cache                = "cache"
	CacheSubmit          = "cache.submit"
	Files                = "files"
	FilesSubmit          = "files.submit"
)
